### ISSUE TITLE
Add support to wallet connect 2.0 providers

### ISSUE THREAD

**Issue by danibonilha** [VGLoic/eth-testing-monorepo#64]
### What is the new or updated feature that you are suggesting?

Wallet connect launched version 2.0 and it has breaking changes regarding providers, there are a couple of new providers and they recommend the usage of this [UniversalProvider](https://github.com/WalletConnect/walletconnect-monorepo/tree/v2.0/providers/universal-provider).  The project I'm working on has already started the migration but the tests are failing due to incompatible providers.

### Why should this feature be included?

Wallet connect v1.0 will sunset soon as stated in this [post](https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e), which will force all users to update to next version.

**Comment by VGLoic** [comment]
Hey @danibonilha ! Thanks a lot for this issue and the informations :)

It is quite a busy week on my side, I'm gonna try to have a look this week-end!

**Comment by VGLoic** [comment]
Hey @danibonilha! I started to take a look at migration to V2 of WalletConnect, as I understand from [their docs](https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0), the migration path in the case of the previous package `@walletconnect/web3-provider` is to go to `@walletconnect/ethereum-provider`

Are you using this `EthereumProvider` or are you using the underlying `UniversalProvider`? :)

I started to implement the mock for the Ethereum Provider, I have some issue as I did not succeed to connect to any of my 5 or 6 wallets using WalletConnect V2 for now but I'll keep trying 😅. Anyway if you use the UniversalProvider directly, there is probably a way to also expose a mock for that.

**Comment by danibonilha** [comment]
Hi @VGLoic thanks for taking a look at it. We were using `web3-provider`, but then we've replaced `web3` with `ethers`. The wallet connect team has [this example Dapp](https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2-with-ethers) with ethers which they use/recommend the `UniversalProvider`. My hunch is that it would be nice to support both `EthereumProvider` and `UniversalProvider`. But In our project we are using `UniversalProvider` only. 
[Here](https://github.com/WalletConnect/web-examples) they have more dapps and wallets examples, I hope it's helpful.

**Comment by VGLoic** [comment]
Nice, thanks a lot! It will help me :)

Sorry if this takes me a bit of time, I'm tackling it as fast as I can 😬

**Comment by VGLoic** [comment]
Hey @danibonilha !

This issue is giving me a hard time ahah

I have not been able to find a wallet supporting Wallet Connect V2, I tried Rainbow, MetaMask Mobile, Trust Wallet and Argent Wallet I think but without luck. I tried on their [live demo app](https://react-dapp-v2-with-ethers.vercel.app/). If you have any wallet and/or code example working, I'll be more than happy 😂 

Also, on the test side, jest has hard time dealing with some deep CommonJS dependency of the `Universal Provider` 😓 

I'll continue digging on that of course :)

**Comment by danibonilha** [comment]
Hi @VGLoic that's unfortunate 🥲
Cardstack wallet supports WC V2 [here's the code ](https://github.com/cardstack/cardwallet/blob/develop/cardstack/src/models/wallet-connect.ts) and it's available to be downloaded on mobile app stores, also Wallet Connect has an example wallet that you can find it [here](https://react-wallet.walletconnect.com/). As far as an example with universal provider, I have this [PR open](https://github.com/cardstack/cardstack/pull/3584).

Hope it helps!

**Comment by VGLoic** [comment]
Hey! Small update, so there is currently an issue between one of the dependency of Universal Provider and Jest, the related issue is https://github.com/WalletConnect/walletconnect-monorepo/issues/1749

At least there is an issue that I can follow now and I'll try the temporary fixes for it, keeping you updated!

**Comment by VGLoic** [comment]
Hey @danibonilha!

Very sorry for the late message!

I unfortunately did not take the time to work on this issue and I will no longer maintain this repository.

Thanks again for the time you took on this issue and to have used this package.

Have a great day!
